/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package belajarMenampilkanGambar;

import java.awt.CardLayout;
import javax.swing.JComboBox;
/**
 *
 * @author asus
 */
public class TampilanGambar extends javax.swing.JFrame {

    /**
     * Creates new form TampilanGambar
     */
    public TampilanGambar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel = new javax.swing.JPanel();
        btnKiana = new javax.swing.JButton();
        btnMei = new javax.swing.JButton();
        btnBronya = new javax.swing.JButton();
        btnSeele = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        imagePanel = new javax.swing.JPanel();
        kianaLB = new javax.swing.JLabel();
        meiLB = new javax.swing.JLabel();
        bronyaLB = new javax.swing.JLabel();
        seeleLB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonPanel.setBackground(new java.awt.Color(0, 0, 204));
        buttonPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Aplikasi Penampil Gambar atau GIF"));

        btnKiana.setText("Kiana");
        btnKiana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKianaActionPerformed(evt);
            }
        });
        buttonPanel.add(btnKiana);

        btnMei.setText("Mei");
        btnMei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMeiActionPerformed(evt);
            }
        });
        buttonPanel.add(btnMei);

        btnBronya.setText("Bronya");
        btnBronya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBronyaActionPerformed(evt);
            }
        });
        buttonPanel.add(btnBronya);

        btnSeele.setText("Seele");
        btnSeele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeeleActionPerformed(evt);
            }
        });
        buttonPanel.add(btnSeele);

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        buttonPanel.add(btnKeluar);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_START);

        imagePanel.setLayout(new java.awt.CardLayout(10, 10));

        kianaLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/belajarMenampilkanGambar/Kiana.gif"))); // NOI18N
        imagePanel.add(kianaLB, "Kiana");

        meiLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/belajarMenampilkanGambar/Mei.gif"))); // NOI18N
        imagePanel.add(meiLB, "Mei");

        bronyaLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/belajarMenampilkanGambar/Bronya.gif"))); // NOI18N
        bronyaLB.setPreferredSize(new java.awt.Dimension(316, 400));
        imagePanel.add(bronyaLB, "Bronya");

        seeleLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/belajarMenampilkanGambar/Seele.jpg"))); // NOI18N
        seeleLB.setToolTipText("");
        imagePanel.add(seeleLB, "Seele");

        getContentPane().add(imagePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnKianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKianaActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)imagePanel.getLayout();
        card.show(imagePanel, "Kiana");
    }//GEN-LAST:event_btnKianaActionPerformed

    private void btnMeiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMeiActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)imagePanel.getLayout();
        card.show(imagePanel, "Mei");
    }//GEN-LAST:event_btnMeiActionPerformed

    private void btnBronyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBronyaActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)imagePanel.getLayout();
        card.show(imagePanel, "Bronya");
    }//GEN-LAST:event_btnBronyaActionPerformed

    private void btnSeeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeeleActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)imagePanel.getLayout();
        card.show(imagePanel, "Seele");
    }//GEN-LAST:event_btnSeeleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TampilanGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TampilanGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TampilanGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TampilanGambar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TampilanGambar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bronyaLB;
    private javax.swing.JButton btnBronya;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnKiana;
    private javax.swing.JButton btnMei;
    private javax.swing.JButton btnSeele;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JLabel kianaLB;
    private javax.swing.JLabel meiLB;
    private javax.swing.JLabel seeleLB;
    // End of variables declaration//GEN-END:variables
}
